nextflow run main.nf \
-resume \
--reads "nf-core-rnaseq-data/*fastq.gz" \
--max_cpus 2 --max_memory 8.GB \
--single_end \
--subsampFilesizeThreshold 4000000 \
--fasta 'https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/reference/genome.fa' \
--gtf 'https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/reference/genes.gtf' \
--hbadeals_metadata https://gist.githubusercontent.com/cgpu/16ee705fd8506b4bccfbb296705dec65/raw/e1fc97e5d53d3b3ed1554fdd583f2812bed14332/metadata_masterfile.csv \
--email chatzipantsiou@gmail.com \
-profile docker