nextflow run main.nf \
-resume \
--reads 'nf-core-rnaseq-data/*.gz' \
--max_cpus 2 \
--max_memory 8.GB \
--single_end \
--subsampFilesizeThreshold 4000000 \
--fasta 'genome.fa' \
--gtf 'genes.gtf' \
--assetsDir $PWD \
--email chatzipantsiou@gmail.com \
-profile docker